import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { UserProvider } from "@/context/UserContext";
import AccessControl from "@/components/AcessControl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Classificação inteligente",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <UserProvider>
          <main className="min-h-screen bg-gray-100">
            <Nav />
            <AccessControl>{children}</AccessControl>
          </main>
        </UserProvider>
      </body>
    </html>
  );
}
