import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { getUserLogon } from "@/lib/getUserLogon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Classificação inteligente",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const userLogon = await getUserLogon();
  console.log(userLogon);
  
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <main className="min-h-screen bg-gray-100">
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
}
